name: skybluelangues.
favicon: null
layout_spectrum: 0.40205307165160775
typography_spectrum: 0.9187450229655951
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8429714215453714
  lightness: 0.7592211009468883
  saturation: 0.9019541179295629
  rhythmicContrast: 0.31366649316623807
purpose: []
